### ISSUE TITLE
[Feature request] Export driver classes

### ISSUE THREAD

**Issue by xfg** [saintedlama/mongoist#10]
Can you add an export of the driver classes as the official driver [do](https://github.com/mongodb/node-mongodb-native/blob/3.0.0/index.js#L13-L29)? I need this feature for unit testing when I want to mock some prototype methods.

**Comment by saintedlama** [comment]
Only mongojs driver classes needed or mongodb driver classes needed too?

**Comment by xfg** [comment]
I think we should export only mongodb driver classes without mongojs especially considering that mongojs is devDependency.

**Comment by saintedlama** [comment]
Prototypes are available in version 1.6 released to npm 🎉

**Comment by xfg** [comment]
@saintedlama thanks for work but now other problem appears because of proxy is used. I want to create my module for example
```javascript
/* lib/db.js */
const mongoist = require('mongoist');
module.exports = mongoist(...);
```
and then to use `db.Cursor` and etc. anywhere in my code but it is impossible because instead `Cursor` I   will [always](https://github.com/saintedlama/mongoist/blob/master/index.js#L22) get `Collection`.

It is can fix if add into proxy handler something like this
```javascript
if (module.exports.hasOwnProperty(prop)) {
  return module.exports[prop];
}
```
or give up from proxy magic and use `db.collection(name)` instead `db.name` as the official mongodb driver do but there is a risk to break a backward compatibility in both cases.

**Comment by saintedlama** [comment]
You can access the prototypes by propagating them to the exports in db.js

```js
/* lib/db.js */
const mongoist = require('mongoist');

module.exports = mongoist('...');

module.exports.Database = mongoist.Database;
module.exports.Collection = mongoist.Collection;
module.exports.Cursor = mongoist.Cursor;
module.exports.Bulk = mongoist.Bulk;
```

Now you can access the prototypes from everywhere you're using `db.js`

```js
const db = require('./lib/db');

// Use the prototype
console.log(db.Database);
```

Or don't propagate the prototypes just do

```js
const db = require('./lib/db');
const mongoist = require('mongoist');

// Use the prototype
console.log(mongoist .Database);
```

**Comment by xfg** [comment]
@saintedlama first option will not work and second option looks like a dirty solution. It would be nice if it worked like in the native mongodb driver.

**Comment by saintedlama** [comment]
Hi @xfg - first version is working - see gist https://gist.github.com/saintedlama/53b228e6ef2ef650afe3bdd9c5246429

Second version is not a dirty workaround since exported prototypes are used directly from the module that exports the prototype. What exactly do you plan to achieve?

**Comment by xfg** [comment]
@saintedlama thanks it works.
