### ISSUE TITLE
`db.collection.findAsCursor` projection param is ignored

### ISSUE THREAD

**Issue by greegus** [saintedlama/mongoist#12]
`db.collection.findAsCursor` projection parameter is ignored in v1.7.0. Looking into the `collections.js` file shows that you would actually need to call the method as `db.collection.findAsCursor({...}, {projection: {...}})` in order to get it processed. I do believe that this does not follow the current documentation, nor is intentional.

**Comment by saintedlama** [comment]
Thanks for reporting the bug. Fixed in version `1.7.1` 🎉
