### ISSUE TITLE
witth findAsCursor projection is not used ?

### ISSUE THREAD

**Issue by asociadoC** [saintedlama/mongoist#13]
Hi there, 

seems there is an issue when using findAsCursor, at least for me I can do what I want, I always get the _id field, same with all other fields I try to exclude. 

example : 

`    
try {
        results = await db.issues.findAsCursor(
            {
            },
            {
                _id : false,
                owner : false,
            }).sort({
                reliability : -1,
                percent : -1,
            }).toArray();
    } catch (error) {
        throw (error);
    }
`

When trying this, and outputting with 

`
    if (issues = await getIssues()) {
        for (let issue of issues) {
            log (issue);
`

I get the _id and also owner displayed.

AM I doing something wrong or is there an issue. 

best regards

**Comment by saintedlama** [comment]
We fixed a bug in version 1.7 related to projections and shipped version 1.7.1 to fix the projections bug. Could you checkout if this bug still exists in version 1.7.1 ?

**Comment by asociadoC** [comment]
Hi there, 

thanks for your reply ! Yes, it seems in 1.7.1 the problem does NOT exist anymore.
I was not aware of that npm fixed my version to 1.5.x, very embarrassing ;) 

Thanks and best regards
