### ISSUE TITLE
Breaking API change from 1.5.1 to 1.6.0

### ISSUE THREAD

**Issue by ghmeier** [saintedlama/mongoist#14]
Taking a look at the recent API changes, it looks like a breaking change was introduced between versions `1.5.1` and `1.6.0`. Previously you could use `mongoist` with a existing `mongojs>=1.4.1` connections since they both expect `mongodb@2.X` connections under the hood. However, version `1.6` instead expects `mongodb@3.X` connections along with its breaking changes to the `find` and `findOne` api. This means that `mongoist@1.6.1` no longer supports `mongojs` connections due to mongodb's breaking API changes.

As a solution, it'd be great to include information about the breaking change in the changelog and publish v2.0 of the module. Alternatively we could find a way to distinguish between 2.X and 3.X mongodb drivers.

**Comment by saintedlama** [comment]
1.7.0 was a "hidden breaking" change minor release 😢 

Fixed breaking changes in projections with mongojs version `1.7.2`

**Comment by ghmeier** [comment]
Thanks so much! It was a pretty weird case to catch in review, so glad to bring it up.
