### ISSUE TITLE
Proxy collisions with `Database` class instances

### ISSUE THREAD

**Issue by chuym** [saintedlama/mongoist#17]
*mongoist version: 1.7.2* but I believe this is problem affects older versions.

The problem is that the `Database` object instance created with `mongoist` has quite a few instance properties whose name can be somewhat commonly used as collection names, this causes the proxy functionality to break. For example:

[this.features](https://github.com/saintedlama/mongoist/blob/ee5c9e19ba050a5a5ca1fe621a7ed4453578a03e/lib/database.js#L27) - means you cannot reference to a `features` collection in your database via Proxy.

Besides this one, `options`, `client`, `connection` and `domain` (this one introduced by extending `EventEmitter` can probably be considered very plausible collection names.

**Comment by saintedlama** [comment]
Thanks for reporting this issue, again a hidden breaking change. You can deal with this issue by using the `collection` function to get a collection without using the proxy shorthand. Will fix it in the next release by using `_` prefix for private fields to avoid name conflicts a bit better

**Comment by bradvogel** [comment]
@saintedlama would you take a PR to fix this? This is causing bugs in our codebase.

**Comment by saintedlama** [comment]
@bradvogel would appreciate a PR for this issue. Thought about circumventing that problem by using prefix `$` for private fields (See https://docs.mongodb.com/manual/reference/limits/#naming-restrictions)
