### ISSUE TITLE
Consider relaxing engine requirement

### ISSUE THREAD

**Issue by wearhere** [saintedlama/mongoist#3]
Hi, thanks for this package! Does this package strictly require Node 8.4, or would you consider relaxing the [engine requirement](https://github.com/saintedlama/mongoist/blob/d532e58/package.json#L7)? `async/await` support was added in Node 7.6.0 (hover over 7.10.1 at top [here](http://node.green/) to see).

It's even possible to use `async/await` even in Node 6 if you use [transpilation](https://babeljs.io/docs/plugins/transform-async-to-generator/)—though typically packages don't transpile their dependencies, so, since this package [internally uses `async/await`](https://github.com/saintedlama/mongoist/blob/93a4db3d2ee03ae7ff85ca8ffb33e9384876843f/lib/bulk.js#L69), supporting the latter would require this package transpile _itself_ before publishing. We would be glad to add support for that if you would consider it. In our own packages we are readying for the upgrade to Node 8 by transpiling pre-publish and switching between the transpiled and untranspiled versions at runtime, using a shim like

```js
// index.js
// This file was created by a script of ours that we would be glad to publish.
// We have an automatic way of removing the shim when transpilation is no longer required too.
const semver = require('semver');

let main;
if (semver.lt(process.version, '7.6.0')) {
  main = require('./dist/node/index.js');
} else {
  main = require('./src/node/index.js');
}
module.exports = main;
```

**Comment by saintedlama** [comment]
Relaxed the engine requirement to node.js >=6 by removing all async/await code from non test files. Test files however will use async and await so travis will not test this project against node 6 and 7 currently. If you could help running the tests on node 6 and 7 by only transpiling the tests that would be great 👍

**Comment by wearhere** [comment]
Wow thanks for the speedy fix @saintedlama and especially for rewriting bulk execution to not use `async/await`, I'm bowled over! We'll look into adding Node 6 and 7 support for the tests. I'll file a separate issue for that though and close this.
