### ISSUE TITLE
Run tests on Node 6 and 7

### ISSUE THREAD

**Issue by wearhere** [saintedlama/mongoist#4]
Follow-up to https://github.com/saintedlama/mongoist/issues/3.

The tests use `async/await` so this would involve transpiling them and switching between the transpiled and untranspiled versions at runtime.

**Comment by saintedlama** [comment]
Tests are running on node 6 and 7 - see travis https://travis-ci.org/saintedlama/mongoist

**Comment by wearhere** [comment]
Whoa! 🙌
