### ISSUE TITLE
SyntaxError in readme

### ISSUE THREAD

**Issue by hontas** [saintedlama/mongoist#5]
`await` keyword can only appear inside an async function, not like it's presented in sections: *mongojs, examples, bulk* and *database commands*.

Solutions:
- Wrap code in an `aiife` (async iife): `(async () => { /* fn body */  }())`
- Add a comment: `// inside async function`
- Or an even better solution

As **not** to cause confusion for those it **isn't** obvious to ;)

**Comment by lindakatcodes** [comment]
Made a pull request for this! I think a simple line at the beginning of the examples area to explain to call them inside an async function should be fine. I can add a link to an example if you've got a good document you'd want in there. Let me know if you'd like me to adjust anything!

**Comment by saintedlama** [comment]
Fixed by @lindakatcodes
